### ISSUE TITLE
Code fails when a directory exists inside data folder

### ISSUE THREAD

**Issue by haluft** [explorerjs32/rho_data_reduction_pipeline#6]
If you try to run the code and there is a folder inside the folder it is navigating through in the function get_frame_info(), it will crash when it tries to read a directory as a file. I ran into this whenever I reran the code after having created the reduced image folder. The solution would be to check if the file is a dir in get_frame_info() and skip it if it is a dir. This is a more minor issue that can be fixed later I just wanted to document it. 

Depending on the format of the raw data we get some data may be inside folders so we would have to build for that possibility (if that turns out to be true) in which case get_frame_info() has to be altered or the program may have to become recursive on some level (creating reduced folders inside each one, or creating nesting reduced folders?) or we still just create one reduced folder that has all the data at the same level.

**Comment by explorerjs32** [comment]
Thank you Hannah, for pointing out this issue with the get_frame_info() function. I'll look into this and make sure it reads only files within the data directory, ignoring any sub-directories within it.

Also, for those times where data from a single night is stored in different folders, I have possible solutions where we can parse more than one data directories, then the get_frame_info() function can group the data from all directories. The storing of reduced frames can be done within the directory belonging to the date when the observations were started, and this can also be reported on the data reduction report file at the end.

We can look into these modifications next time
